### ISSUE TITLE
SIGALRM attribute is not available on windows, causes program to fail

### ISSUE THREAD

**Issue by seahyx** [mcdulltii/String-encrypt#1]
Issue: Running the program on windows will cause it to fail, as `signal.SIGALRM` does not exist for windows. From the python documentation for [`signals.alarm()`](https://docs.python.org/3/library/signal.html#signal.alarm), 

> Availability: Unix

Related StackOverflow questions:
https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows

Remedy: Possibly by implementing a substitute for windows. See: 
https://stackoverflow.com/questions/8420422/python-windows-equivalent-of-sigalrm

Full Traceback:

```Python traceback
> py ./parser.py -s hello -e 10 -l py -o hello.py
Traceback (most recent call last):
  File "./parser.py", line 313, in <module>
    main()
  File "./parser.py", line 297, in main
    py()
  File "./parser.py", line 194, in py
    encode_seq, rand_seq, output_seq = find_pos(input_list, len(encode_func)-3)
  File "./parser.py", line 115, in find_pos
    signal.signal(signal.SIGALRM, timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by mcdulltii** [comment]
Fixed issue by replacing platform dependent timeout code with code from
https://stackoverflow.com/a/37648512
